#pragma once

// copy from glfw3.h
/* Mouse Key codes */
#define LEAF_MOUSE_BUTTON_1 0
#define LEAF_MOUSE_BUTTON_2 1
#define LEAF_MOUSE_BUTTON_3 2
#define LEAF_MOUSE_BUTTON_4 3
#define LEAF_MOUSE_BUTTON_5 4
#define LEAF_MOUSE_BUTTON_6 5
#define LEAF_MOUSE_BUTTON_7 6
#define LEAF_MOUSE_BUTTON_8 7
#define LEAF_MOUSE_BUTTON_LAST LEAF_MOUSE_BUTTON_8
#define LEAF_MOUSE_BUTTON_LEFT LEAF_MOUSE_BUTTON_1
#define LEAF_MOUSE_BUTTON_RIGHT LEAF_MOUSE_BUTTON_2
#define LEAF_MOUSE_BUTTON_MIDDLE LEAF_MOUSE_BUTTON_3
